### ISSUE TITLE
Tests unitaires avec chargement de fichiers JSON

### ISSUE THREAD

**Issue by Bludwarf** [Bludwarf/music-diagram-generator#9]
KO pour l'instant : 

```
Chrome 122.0.0.0 (Windows 10) AlsExtractor should get sample duration from Petit papillon FAILED
        Error: Text data outside of root node.
        Line: 0
        Column: 9
        Char: D
        error properties: Object({ note: Error: Text data outside of root node.
        Line: 0
        Column: 9
        Char: D })
            at error (node_modules/sax/lib/sax.js:652:10)
            at strictFail (node_modules/sax/lib/sax.js:678:7)
            at SAXParser.write (node_modules/sax/lib/sax.js:1036:15)
            at xml2js (node_modules/xml-js/lib/xml2js.js:346:12)
            at Object.xml2json (node_modules/xml-js/lib/xml2json.js:13:8)
            at src/app/als/als-importer.ts:65:31
            at Generator.next (<anonymous>)
            at asyncGeneratorStep (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
            at apply (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:1)
            at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:368:26)
Chrome 122.0.0.0 (Windows 10): Executed 5 of 25 (1 FAILED) (0 secs / 0.048 secs)
```

**Comment by Bludwarf** [comment]
Correction également du test de SongComponent.
